package com.goldenbike.model.domain;

import java.io.Serializable;

/**
 * Domain Reservation class that links a customer, a bike and reservation times 
 * @author Jorge Paz
 */
@SuppressWarnings("serial")
public class Reservation implements Serializable {

	/**Customer that reserved the bike**/
	private Customer customer;
	
	/**Bike that was reserved**/
	private Bike bike;
	
	/**Date and times of reservation**/
	private ReservationTimes reservationTimes;
	
	/**
	 * Default constructor
	 */
	public Reservation() {
		
	}

	/**
	 * Constructor
	 * @param customer
	 * @param bike
	 * @param reservationTimes
	 */
	public Reservation(Customer customer, Bike bike, ReservationTimes reservationTimes) {
		this.customer = customer;
		this.bike = bike;
		this.reservationTimes = reservationTimes;
	}

	/**
	 * @return Returns the customer
	 */
	public Customer getCustomer() {
		return customer;
	}

	/**
	 * Sets the customer
	 * @param customer
	 */
	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	/**
	 * @return Returns the bike
	 */
	public Bike getBike() {
		return bike;
	}

	/**
	 * Sets the bike
	 * @param bike
	 */
	public void setBike(Bike bike) {
		this.bike = bike;
	}

	/**
	 * @return Returns the reservation times
	 */
	public ReservationTimes getReservationTimes() {
		return reservationTimes;
	}

	/**
	 * Sets the reservation times
	 * @param reservationTimes
	 */
	public void setReservationTimes(ReservationTimes reservationTimes) {
		this.reservationTimes = reservationTimes;
	}

	/**
	 * Returns reservation object details in a String
	 */
	public String toString() {
		return "Reservation [customer=" + customer + ", bike=" + bike + ", reservationTimes=" + reservationTimes + "]";
	}

	/**
	 * Auto-Generated by IDE
	 */
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((bike == null) ? 0 : bike.hashCode());
		result = prime * result + ((customer == null) ? 0 : customer.hashCode());
		result = prime * result + ((reservationTimes == null) ? 0 : reservationTimes.hashCode());
		return result;
	}

	/**
	 * @param reservation
	 * @return Boolean
	 */
	public boolean equals(Reservation reservation) {
		if(!customer.equals(reservation.customer))
			return false;
		if(!bike.equals(reservation.bike))
			return false;
		if(!reservationTimes.equals(reservation.reservationTimes))
			return false;
		return true;
	}
	
	/**
	 * @return Returns Boolean
	 */
	public boolean validate() {
		if(customer == null)
			return false;
		if(bike == null)
			return false;
		if(reservationTimes == null)
			return false;
		return true;
	}
	
}
